apiVersion: v1
kind: Service
metadata:
  namespace: {{ .Release.Namespace }}
  name: {{ .Values.service.name }}
  labels:
    {{- include "postgres.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "postgres.selectorLabels" . | nindent 4 }}
  ports:
  - name: postgres
    protocol: TCP
    port: {{ .Values.postgres.ports.postgres }}
    targetPort: 5432
  - name: metrics
    protocol: TCP
    port: {{ .Values.postgres.ports.metrics }}
    targetPort: 9187